Update model_uploader.yml
Signed-off-by: Thanawan Atchariyachanvanit <latchari@amazon.com>

diff --git a/.github/workflows/model_uploader.yml b/.github/workflows/model_uploader.yml
--- a/.github/workflows/model_uploader.yml
+++ b/.github/workflows/model_uploader.yml
@@ -48,11 +48,11 @@ jobs:
   init-workflow-var:
     runs-on: 'ubuntu-latest'
     steps:
-    - name: Fail if branch is not main
-      if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
-      run: |
-         echo "This workflow should only be triggered on a default branch"
-         exit 1
+#     - name: Fail if branch is not main
+#       if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
+#       run: |
+#          echo "This workflow should only be triggered on a default branch"
+#          exit 1
     - name: Initiate model_folder
       id: init_model_folder
       run: |
