Update model_uploader.yml
Signed-off-by: Thanawan Atchariyachanvanit <latchari@amazon.com>

diff --git a/.github/workflows/model_uploader.yml b/.github/workflows/model_uploader.yml
--- a/.github/workflows/model_uploader.yml
+++ b/.github/workflows/model_uploader.yml
@@ -47,12 +47,12 @@ jobs:
   init-workflow-var:
     runs-on: 'ubuntu-latest'
     steps:
-    - name: Fail if branch is not main
-      if: github.ref != 'refs/heads/workflow-for-review' # TO-BE-CHANGED
-      #if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
-      run: |
-        echo "This workflow should not be triggered with workflow_dispatch on a branch other than main"
-        exit 1
+#     - name: Fail if branch is not main
+#       if: github.ref != 'refs/heads/workflow-for-review' # TO-BE-CHANGED
+#       #if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
+#       run: |
+#         echo "This workflow should not be triggered with workflow_dispatch on a branch other than main"
+#         exit 1
     - name: Initiate model_folder
       id: init_model_folder
       run: |
